name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Puedes cambiar a la rama donde quieres que se ejecute
    paths:
      - '**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Find changed Dockerfiles
        id: find_dockerfiles
        run: |
          # Encuentra Dockerfiles modificados en el último commit comparado al anterior
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep 'Dockerfile')
          echo "Changed Dockerfiles: $CHANGED_FILES"
          # Convertir a un array que pueda ser leído por GitHub Actions
          echo "dockerfiles=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Build and push Docker images
        if: env.dockerfiles != ""
        run: |
          for dockerfile in ${{ env.dockerfiles }}
          do
            # Extraer el directorio donde está el Dockerfile
            dir=$(dirname "$dockerfile")
            # Usar el nombre del directorio como etiqueta (tag) en Docker Hub
            image_name="${{ secrets.DOCKER_USERNAME }}/$(basename $dir)"
            # Construir la imagen
            docker build -t "$image_name:latest" "$dir"
            # Subir la imagen
            docker push "$image_name:latest"
          done

